"""create_user_table

Revision ID: bfefa42f538f
Revises: bd90c9d6799b
Create Date: 2026-07-06 10:20:20.395464

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'bfefa42f538f'
down_revision: Union[str, Sequence[str], None] = 'bd90c9d6799b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
